--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonwynn10/MyPlot
projects:
  MyPlot:
    icon: "icon.png"
    path: ""
    libs:
      - src: Falkirks/spoondetector/spoondetector
        version: ^0.0.1
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3.0
...